services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: snapurl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: ["snapurl_pg:/var/lib/postgresql/data"]
volumes:
  snapurl_pg:
